# terminal.ps1 - Configure Windows Terminal profiles

. "$PSScriptRoot\..\lib\common.ps1"

$script:TerminalConfigDir = "$PSScriptRoot\..\configs\terminal"

# Well-known Microsoft-owned GUIDs auto-generated by Windows Terminal.
# Profiles matching these (or carrying a `source` field) are skipped so we
# never overwrite the user's tweaks to built-ins.
$script:BuiltinTerminalGuids = @(
    "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}"  # Windows PowerShell
    "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}"  # Command Prompt
)

function Get-WindowsTerminalSettingsPath {
    # Find Windows Terminal settings path
    $terminalPackages = Get-ChildItem -Path "$env:LOCALAPPDATA\Packages" -Filter "Microsoft.WindowsTerminal*" -Directory -ErrorAction SilentlyContinue

    foreach ($pkg in $terminalPackages) {
        $settingsPath = "$($pkg.FullName)\LocalState\settings.json"
        if (Test-Path $settingsPath) {
            return $settingsPath
        }
    }

    return $null
}

function Get-CustomTerminalProfiles {
    # Reads configs/terminal/profiles.json and returns only the entries we own:
    # profiles without a `source` field and not in the built-in GUID list.
    param(
        [Parameter(Mandatory)]
        [string]$SourceProfilesPath
    )

    $customSettings = Get-Content -Path $SourceProfilesPath -Raw | ConvertFrom-Json
    return @($customSettings.profiles.list | Where-Object {
        (-not $_.PSObject.Properties.Match('source').Count) -and
        ($script:BuiltinTerminalGuids -notcontains $_.guid)
    })
}

function Install-TerminalProfiles {
    <#
    .SYNOPSIS
        Merges custom profiles from configs/terminal/profiles.json into Windows Terminal settings
    #>
    param(
        [switch]$DryRun,
        [switch]$Force
    )

    Write-SetupLog "Configuring Windows Terminal..." "INFO"

    $settingsPath = Get-WindowsTerminalSettingsPath

    if (-not $settingsPath) {
        Write-SetupLog "Windows Terminal is not installed" "WARNING"
        Write-SetupLog "Install it from Microsoft Store: https://aka.ms/terminal" "INFO"
        return $false
    }

    Write-SetupLog "Found Windows Terminal settings at: $settingsPath" "INFO"

    $sourceProfilesPath = "$script:TerminalConfigDir\profiles.json"
    if (-not (Test-Path $sourceProfilesPath)) {
        Write-SetupLog "Source profiles not found: $sourceProfilesPath" "ERROR"
        return $false
    }

    $customProfiles = Get-CustomTerminalProfiles -SourceProfilesPath $sourceProfilesPath
    if (-not $customProfiles -or $customProfiles.Count -eq 0) {
        Write-SetupLog "No custom profiles found in $sourceProfilesPath" "WARNING"
        return $true
    }

    if ($DryRun) {
        Write-SetupLog "[DRY RUN] Would merge $($customProfiles.Count) custom profile(s) into Windows Terminal settings" "INFO"
        foreach ($p in $customProfiles) {
            Write-SetupLog "[DRY RUN]   - $($p.name) ($($p.guid))" "INFO"
        }
        return $true
    }

    try {
        # Backup existing settings
        Backup-Item -Path $settingsPath | Out-Null

        # Read existing settings
        $existingSettings = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json

        # Get existing profiles list
        $existingProfiles = @($existingSettings.profiles.list)

        foreach ($customProfile in $customProfiles) {
            # Check if profile already exists
            $existingProfile = $existingProfiles | Where-Object { $_.guid -eq $customProfile.guid }

            if ($existingProfile) {
                # Replace the existing entry outright with our declared version.
                $index = [array]::IndexOf($existingProfiles, $existingProfile)
                $existingProfiles[$index] = $customProfile
                Write-SetupLog "Updated profile: $($customProfile.name)" "SUCCESS"
            } else {
                # Add new profile
                $existingProfiles += $customProfile
                Write-SetupLog "Added profile: $($customProfile.name)" "SUCCESS"
            }
        }

        # Update profiles list
        $existingSettings.profiles.list = $existingProfiles

        # Update default profile to PowerShell Core if not already set to one of our custom profiles
        $customGuids = $customProfiles | ForEach-Object { $_.guid }
        $defaultProfile = $existingSettings.defaultProfile
        if (-not ($customGuids -contains $defaultProfile)) {
            # Find PowerShell Core profile
            $pwshProfile = $existingProfiles | Where-Object { $_.source -eq "Windows.Terminal.PowershellCore" }
            if ($pwshProfile) {
                $existingSettings.defaultProfile = $pwshProfile.guid
                Write-SetupLog "Set default profile to PowerShell Core" "INFO"
            }
        }

        # Write updated settings
        $existingSettings | ConvertTo-Json -Depth 20 | Set-Content -Path $settingsPath -Encoding UTF8

        Write-SetupLog "Windows Terminal profiles configured successfully" "SUCCESS"
        return $true

    } catch {
        Write-SetupLog "Failed to configure Windows Terminal: $_" "ERROR"
        return $false
    }
}

function Uninstall-TerminalProfiles {
    <#
    .SYNOPSIS
        Removes custom profiles (as declared in configs/terminal/profiles.json) from Windows Terminal settings
    #>
    param(
        [switch]$RemoveAll
    )

    Write-SetupLog "Removing custom Windows Terminal profiles..." "INFO"

    $settingsPath = Get-WindowsTerminalSettingsPath
    if (-not $settingsPath) {
        Write-SetupLog "Windows Terminal settings not found" "INFO"
        return
    }

    $sourceProfilesPath = "$script:TerminalConfigDir\profiles.json"
    if (-not (Test-Path $sourceProfilesPath)) {
        Write-SetupLog "Source profiles not found: $sourceProfilesPath" "ERROR"
        return
    }

    try {
        $settings = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json

        # Derive the removal set from the same JSON the installer uses.
        $customProfiles = Get-CustomTerminalProfiles -SourceProfilesPath $sourceProfilesPath
        $customGuids = $customProfiles | ForEach-Object { $_.guid }

        # Filter out our custom profiles
        $settings.profiles.list = $settings.profiles.list | Where-Object { $_.guid -notin $customGuids }

        # Write updated settings
        $settings | ConvertTo-Json -Depth 20 | Set-Content -Path $settingsPath -Encoding UTF8

        Write-SetupLog "Custom profiles removed from Windows Terminal" "SUCCESS"

    } catch {
        Write-SetupLog "Failed to remove profiles: $_" "ERROR"
    }
}
