"""Global numpad shortcuts via KWin scripting (spec 025, revised).

Registers `Ctrl+Alt+Numpad 1-9` and routes each to the monitor's own D-Bus
scene service.

Why KWin scripting and not a .desktop shortcut
----------------------------------------------
The first implementation used the mechanism every other custom shortcut on this
machine uses: a `.desktop` file plus a `[services][...]` entry in
`kglobalshortcutsrc`. That works — but only from the next login, because the key
*grabs* for service shortcuts are installed when KDE enumerates that file at
session start. Registering the same component later over the KGlobalAccel D-Bus
API puts an entry in the table (the key even reports as claimed) but installs no
grab and leaves no process to notify, so the key does nothing. Both were
verified on the hardware.

KWin's scripting API registers a real grab immediately, and
`kwin_window_position.py` in this project already drives that API, so the
mechanism is established here rather than invented.

The script must stay **loaded**: the shortcuts live exactly as long as it does.
It is reloaded on every monitor start, which makes it self-healing — the app and
its shortcuts cannot drift apart.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
import time

from PyQt6.QtDBus import QDBusConnection, QDBusMessage

import aio_scenes
import scene_service

_log = logging.getLogger(__name__)

KWIN_SERVICE = "org.kde.KWin"
KWIN_SCRIPTING_PATH = "/Scripting"
KWIN_SCRIPTING_IFACE = "org.kde.kwin.Scripting"
KWIN_SCRIPT_IFACE = "org.kde.kwin.Script"

SCRIPT_NAME = "peripheral-battery-monitor-scenes"
# KDE spells numpad keys "Num+N"; verified firing on this hardware.
KEY_TEMPLATE = "Ctrl+Alt+Num+{n}"
ANIM_KEY_TEMPLATE = "Ctrl+Alt+Shift+Num+{n}"


def _script_dir() -> str:
    return os.environ.get("XDG_RUNTIME_DIR") or tempfile.gettempdir()


def _script_path() -> str:
    """A UNIQUE path per install. Never reuse one.

    The obvious design — a stable path, so a reload replaces the previous script
    rather than stacking — does not work: **KWin caches loaded scripts by path**.
    Calling `loadScript` on a path it has seen returns the existing script's id
    without re-reading the file, and `run` on an already-run script does nothing.
    The reload silently no-ops while reporting success at every level:
    `install()` returns True, `isScriptLoaded` returns true, and the file on disk
    is the new one — but the shortcuts in KWin are whatever loaded first.

    Within one session that is invisible, because the first load works. It bites
    across a restart: if the first load of a session fails or registers nothing,
    every later attempt is a cached no-op and the shortcuts cannot be recovered
    without restarting KWin. That is exactly how they broke.

    A unique path forces a real load every time. The previous script is unloaded
    and its file removed, so nothing stacks and nothing accumulates.
    """
    return os.path.join(_script_dir(), f"{SCRIPT_NAME}-{os.getpid()}-{time.time_ns()}.js")


def _stale_script_files() -> list[str]:
    """Leftover generated scripts from earlier runs, for cleanup."""
    directory = _script_dir()
    try:
        names = os.listdir(directory)
    except OSError:
        return []
    return [os.path.join(directory, n) for n in names
            if n.startswith(SCRIPT_NAME) and n.endswith(".js")]


def _key_for(slot: int) -> str:
    """The key sequence for a slot, in whichever bank it belongs to."""
    if slot > aio_scenes.SLOT_MAX:
        return ANIM_KEY_TEMPLATE.format(n=slot - aio_scenes.ANIM_OFFSET)
    return KEY_TEMPLATE.format(n=slot)


def pretty_key(slot: int) -> str:
    """The binding as a human reads it, e.g. "Ctrl+Alt+Shift+Num 1".

    Derived from the same template that registers the shortcut, so the menu
    cannot advertise a key that is not actually bound.
    """
    return _key_for(slot).replace("Num+", "Num ")


def all_slots() -> list[int]:
    return (list(range(aio_scenes.SLOT_MIN, aio_scenes.SLOT_MAX + 1))
            + list(range(aio_scenes.ANIM_MIN, aio_scenes.ANIM_MAX + 1)))


def build_js(slots=None) -> str:
    """The KWin script registering one shortcut per slot.

    Each callback is built in its own closure: a bare loop variable would leave
    every shortcut pointing at the last slot.
    """
    if slots is None:
        slots = all_slots()
    lines = [
        "// Generated by peripheral-battery-monitor (spec 025). Do not edit;",
        "// it is rewritten on every monitor start.",
        # print() reaches the journal as kwin_wayland output. Without it the KWin
        # half of the chain is invisible: when a scene did not apply there was no
        # way to tell a key that never fired from one that fired and failed to
        # reach the monitor, which cost a long diagnosis. Registration is logged
        # too, so a shortcut that KWin accepted but did not grab is visible.
        "print('aio-scenes: registering ' + %d + ' shortcuts');" % len(slots),
    ]
    for slot in slots:
        key = _key_for(slot)
        lines.append(
            "(function(slot, key) {\n"
            f"    registerShortcut('AIOScene' + slot,\n"
            f"                     'AIO lighting scene ' + slot,\n"
            f"                     key,\n"
            "                     function() {\n"
            "        print('aio-scenes: shortcut fired, slot ' + slot);\n"
            f"        callDBus({json.dumps(scene_service.SERVICE)},\n"
            f"                 {json.dumps(scene_service.PATH)},\n"
            f"                 {json.dumps(scene_service.IFACE)},\n"
            "                 'Apply', slot);\n"
            "    });\n"
            f"}})({slot}, {json.dumps(key)});"
        )
    return "\n".join(lines) + "\n"


class SceneShortcuts:
    """Loads and owns the KWin script for the life of the app."""

    def __init__(self):
        self._bus = QDBusConnection.sessionBus()
        self._path: str | None = None

    def _call(self, path: str, iface: str, method: str, *args):
        msg = QDBusMessage.createMethodCall(KWIN_SERVICE, path, iface, method)
        if args:
            msg.setArguments(list(args))
        reply = self._bus.call(msg)
        if reply.type() != QDBusMessage.MessageType.ReplyMessage:
            _log.warning("kwin_call_failed method=%s err=%s", method,
                         reply.errorMessage())
            return None
        out = reply.arguments()
        return out[0] if out else None

    def install(self, slots=None) -> bool:
        """Write and load the script. False when KWin is unavailable."""
        if not self._bus.isConnected():
            _log.warning("scene_shortcuts_no_session_bus")
            return False

        path = _script_path()
        try:
            with open(path, "w") as f:
                f.write(build_js(slots))
        except OSError as e:
            _log.warning("scene_shortcuts_write_failed path=%s err=%s", path, e)
            return False

        # Unload the previous copy (by its own path) and drop stale files. A new
        # unique path is used for this load, so nothing can be served from KWin's
        # by-path cache.
        if self._path:
            self._call(KWIN_SCRIPTING_PATH, KWIN_SCRIPTING_IFACE, "unloadScript", self._path)
        for stale in _stale_script_files():
            if stale == path:
                continue
            self._call(KWIN_SCRIPTING_PATH, KWIN_SCRIPTING_IFACE, "unloadScript", stale)
            try:
                os.unlink(stale)
            except OSError:
                pass

        script_id = self._call(KWIN_SCRIPTING_PATH, KWIN_SCRIPTING_IFACE,
                               "loadScript", path)
        if script_id is None:
            return False
        try:
            self._call(f"{KWIN_SCRIPTING_PATH}/Script{int(script_id)}",
                       KWIN_SCRIPT_IFACE, "run")
        except (TypeError, ValueError):
            _log.warning("scene_shortcuts_bad_script_id id=%r", script_id)
            return False

        # Verify rather than assume. Reporting success on an unverified load is
        # what let a silently cached no-op look healthy for hours.
        loaded = self._call(KWIN_SCRIPTING_PATH, KWIN_SCRIPTING_IFACE,
                            "isScriptLoaded", path)
        if loaded is not True:
            _log.warning("scene_shortcuts_load_unverified path=%s reply=%r", path, loaded)
            return False

        self._path = path
        _log.info("scene_shortcuts_installed path=%s slots=%d", path,
                  len(slots if slots is not None else all_slots()))
        return True

    def remove(self):
        """Unload the script, dropping the shortcuts with it."""
        if not self._path:
            return
        self._call(KWIN_SCRIPTING_PATH, KWIN_SCRIPTING_IFACE,
                   "unloadScript", self._path)
        try:
            os.unlink(self._path)
        except OSError:
            pass
        self._path = None
